server:
  port: 8095

spring:
  cloud:
    gateway:
      routes:
      - id: customer-service
        uri: http://localhost:8091/
        predicates:
        - Path=/customers/**
      - id: product-service
        uri: http://localhost:8092/
        predicates:
        - Path=/bankAccounts/**,/credits/**
      - id: transaction-service
        uri: http://localhost:8093/
        predicates:
        - Path=/transactions/**
      - id: report-service
        uri: http://localhost:8096/
        predicates:
        - Path=/reports/**
      - id: card-service
        uri: http://localhost:8097/
        predicates:
        - Path=/debitcards/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8094/eureka
