server:
  port: 8095

spring:
  cloud:
    gateway:
      routes:
      - id: CUSTOMER-SERVICE
        uri: localhost:8091/
        predicates:
        - Path=/customers/**
      - id: product-service
        uri: http://localhost:8092
        predicates:
        - Path=/products/bankAccounts/**
      - id: product-service
        uri: http://localhost:8092
        predicates:
        - Path=/products/credits/**
      - id: transaction-service
        uri: http://localhost:8093
        predicates:
        - Path=/transactions/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8094/eureka
