server:
  port: 8095

spring:
  cloud:
    gateway:
      routes:
      - id: customer-service
        uri: https://localhost:8091
        predicates:
        - Path=/customers/**
  application:
    name: apigateway-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8094/eureka
