server:
  port: 8095
  ssl:
    ciphers: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

spring:
  cloud:
    gateway:
      routes:
      - id: customer-service
        uri: https://localhost:8091
        predicates:
        - Path=/customers/**
      - id: product-service
        uri: https://localhost:8092
        predicates:
        - Path=/products/bankAccounts/**
      - id: product-service
        uri: https://localhost:8092
        predicates:
        - Path=/products/credits/**
      - id: transaction-service
        uri: https://localhost:8093
        predicates:
        - Path=/transactions/**
  application:
    name: apigateway-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8094/eureka
