server:
  port: 8093
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bank
      
eureka:
  client:
    service-url:
      defaultZone: https://eureka-server-bootcamp.azurewebsites.net
